#!/usr/bin/env python3
# slice9-gen.py - procedural slice-9 frame generator (proof / reference).
# ============================================================================
# Generates a border-image atlas PER SKIN to a KNOWN GEOMETRY, so the four
# slice insets are exact BY CONSTRUCTION (no detection needed). Each frame is
# drawn at 1 art-pixel == 1 source-pixel; the CSS upscales it with
# image-rendering:pixelated, so corners stay crisp at any element size.
#
# This is the cheap, deterministic path for GEOMETRIC game-UI skins. Ornate
# skins (gold filigree, carved stone) take the image-gen path instead: the same
# geometry contract, generated by a model, then normalised by tools/slice9_detect.py.
#
#   python3 slice9-gen.py            # writes ../assets/slice9/<skin>/*.png + atlas.json
#                                    # + ../assets/slice9/_gallery.html (all skins)
#
# Adding a skin = one entry in SKINS. Each skin owns its tile/corner/scale and a
# role->painter map. Painters are built from a generic ring model:
#   make_frame(layers, body, chamfer, pressed)
#     layers: [(thickness, spec), ...] outside-in; spec = rgba | ("bevel", hi, sh)
#     body:   rgba | ("grad", topRGBA, botRGBA) | callable(x,y,w,h)
#     chamfer: NES-style diagonal corner cut (px), 0 = square
# ============================================================================
import json, os

from PIL import Image

OUT_ROOT = os.path.join(os.path.dirname(__file__), "..", "assets", "slice9")
CLEAR = (0, 0, 0, 0)


def hx(s, a=255):
    s = s.lstrip("#")
    return (int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16), a)


def lerp(c0, c1, t):
    return tuple(round(c0[i] + (c1[i] - c0[i]) * t) for i in range(4))


def edge_dist(x, y, w, h):
    return min(x, y, w - 1 - x, h - 1 - y)


def make_frame(layers, body, chamfer=1, pressed=False):
    """Return a px(x,y,w,h)->rgba painter from an outside-in ring spec."""
    def bodycol(x, y, w, h):
        if callable(body):
            return body(x, y, w, h)
        if isinstance(body, tuple) and len(body) == 3 and body[0] == "grad":
            _, top, bot = body
            t = y / (h - 1) if h > 1 else 0
            return lerp(top, bot, t)
        return body

    def px(x, y, w, h):
        # diagonal corner cut (rounded pixel corner)
        if chamfer > 0:
            cx = min(x, w - 1 - x)
            cy = min(y, h - 1 - y)
            if cx + cy < chamfer:
                return CLEAR
        depth = edge_dist(x, y, w, h)
        acc = 0
        for th, spec in layers:
            if depth < acc + th:
                if isinstance(spec, tuple) and spec and spec[0] == "bevel":
                    _, hi, sh = spec
                    top_left = (x + y) < (w - 1)
                    if pressed:
                        return sh if top_left else hi
                    return hi if top_left else sh
                return spec
            acc += th
        return bodycol(x, y, w, h)

    return px


# ----------------------------------------------------------------------------
# SKINS - each maps a library aesthetic to a role->painter set.
# ----------------------------------------------------------------------------
def skin_8bit():
    INK = hx("#1a1c2c"); WHITE = hx("#f4f4f4")
    PANEL = hx("#29366f"); CARD = hx("#3a4a8c")
    FACE = hx("#5b6ee1"); HI = hx("#9aaaff"); SH = hx("#2d3478"); DOWN = hx("#46568c")
    FIELD = hx("#f4f4f4"); FHI = hx("#ffffff"); FSH = hx("#96a0c8")
    return dict(
        id="8bit", label="8-bit generic", library="aesthetic-8-bit-generic",
        tile=24, corner=8, scale=3,
        roles=dict(
            panel=make_frame([(1, INK), (1, WHITE)], PANEL),
            card=make_frame([(1, INK), (1, WHITE)], CARD),
            button=make_frame([(1, INK), (1, ("bevel", HI, SH))], FACE),
            **{"button-active": make_frame([(1, INK), (1, ("bevel", HI, SH))], DOWN, pressed=True)},
            input=make_frame([(1, INK), (1, ("bevel", FHI, FSH))], FIELD, pressed=True),
        ),
    )


def skin_snes():
    OUT = hx("#10183a"); RIM = hx("#6cb8e8")
    HI = hx("#4a6fce"); SH = hx("#1c2a63")
    TOP = hx("#2b3f8f"); BOT = hx("#16234f")
    CTOP = hx("#33489c"); CBOT = hx("#1d2c66")
    FACE = hx("#3b5bbf"); BHI = hx("#6f8fe0"); BSH = hx("#1c2a63"); DOWN = hx("#243a86")
    WELL = hx("#0f1840")
    return dict(
        id="snes", label="16-bit SNES JRPG window", library="aesthetic-pixel-snes-jrpg",
        tile=32, corner=10, scale=2,
        roles=dict(
            panel=make_frame([(1, OUT), (2, RIM), (2, ("bevel", HI, SH))], ("grad", TOP, BOT), chamfer=2),
            card=make_frame([(1, OUT), (2, RIM), (2, ("bevel", HI, SH))], ("grad", CTOP, CBOT), chamfer=2),
            button=make_frame([(1, OUT), (2, ("bevel", BHI, BSH))], FACE, chamfer=2),
            **{"button-active": make_frame([(1, OUT), (2, ("bevel", BHI, BSH))], DOWN, chamfer=2, pressed=True)},
            input=make_frame([(1, OUT), (2, RIM), (1, ("bevel", SH, HI))], WELL, chamfer=2, pressed=True),
        ),
    )


def skin_scifi():
    OUT = hx("#0e2b38"); NEON = hx("#34e3ff")
    BODY = hx("#0a1a26"); BODY2 = hx("#0e2230")
    CARDB = hx("#0c2433")
    BTN = hx("#0c2230"); BDN = hx("#12506a"); BNEON = hx("#34e3ff")
    WELL = hx("#06141d"); WNEON = hx("#1c7d96")
    return dict(
        id="scifi", label="Sci-fi HUD panel", library="aesthetic-arknights-endfield-industrial",
        tile=32, corner=12, scale=2,
        roles=dict(
            panel=make_frame([(1, OUT), (1, BODY), (1, NEON)], ("grad", BODY2, BODY), chamfer=7),
            card=make_frame([(1, OUT), (1, BODY), (1, NEON)], CARDB, chamfer=7),
            button=make_frame([(1, OUT), (1, BTN), (1, BNEON)], BTN, chamfer=6),
            **{"button-active": make_frame([(1, OUT), (1, BDN), (1, BNEON)], BDN, chamfer=6)},
            input=make_frame([(1, OUT), (1, WELL), (1, WNEON)], WELL, chamfer=6),
        ),
    )


def skin_cozy():
    OUTW = hx("#3a2412"); WHI = hx("#b9824c"); WSH = hx("#3a2410"); CREAM = hx("#f6ead0")
    PARCH = hx("#efdcb4"); CARDP = hx("#f6e8c8")
    BFACE = hx("#c9954f"); BHI = hx("#e8c188"); BSH = hx("#6e4422"); BDN = hx("#a87a3c")
    FIELD = hx("#f8efd8"); FHI = hx("#ffffff"); FSH = hx("#c8a86a")
    return dict(
        id="cozy", label="Cozy parchment / wood", library="aesthetic-pixel-modern-cozy",
        tile=28, corner=9, scale=2,
        roles=dict(
            panel=make_frame([(1, OUTW), (2, ("bevel", WHI, WSH)), (1, CREAM)], PARCH, chamfer=2),
            card=make_frame([(1, OUTW), (2, ("bevel", WHI, WSH)), (1, CREAM)], CARDP, chamfer=2),
            button=make_frame([(1, OUTW), (2, ("bevel", BHI, BSH))], BFACE, chamfer=2),
            **{"button-active": make_frame([(1, OUTW), (2, ("bevel", BHI, BSH))], BDN, chamfer=2, pressed=True)},
            input=make_frame([(1, OUTW), (1, ("bevel", FSH, FHI))], FIELD, chamfer=2, pressed=True),
        ),
    )


SKINS = [skin_8bit(), skin_snes(), skin_scifi(), skin_cozy()]


def render(fn, tile):
    img = Image.new("RGBA", (tile, tile), CLEAR)
    px = img.load()
    for y in range(tile):
        for x in range(tile):
            px[x, y] = fn(x, y, tile, tile)
    return img


def build_skin(skin):
    out = os.path.join(OUT_ROOT, skin["id"])
    os.makedirs(out, exist_ok=True)
    tile, corner, scale = skin["tile"], skin["corner"], skin["scale"]
    frames = {}
    for role, fn in skin["roles"].items():
        render(fn, tile).save(os.path.join(out, role + ".png"))
        ctl = role in ("button", "button-active", "input")
        frames[role] = {
            "src": role + ".png",
            "slice": [corner, corner, corner, corner],   # t r b l (source px)
            "fill": True,
            "width": corner * (scale - 1 if ctl else scale),  # controls thinner than panels
            "repeat": "stretch",
            "role": role,
        }
    manifest = {
        "id": skin["id"], "label": skin["label"], "library": skin["library"],
        "tile": tile, "corner": corner, "imageRendering": "pixelated", "frames": frames,
    }
    with open(os.path.join(out, "atlas.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    return manifest


def write_gallery(manifests):
    """Self-maintaining proof page: every skin x role, driven by the manifest
    values (proving the manifest is the single source the render obeys)."""
    secs = []
    for m in manifests:
        cells = []
        for role, fr in m["frames"].items():
            sl = " ".join(str(v) for v in fr["slice"]) + (" fill" if fr.get("fill") else "")
            tag = "button" if "button" in role else ("input" if role == "input" else "div")
            label = {"panel": "Panel", "card": "Card", "button": "Button",
                     "button-active": "Pressed", "input": "Input"}.get(role, role)
            # NB: url() in a custom property resolves relative to the STYLESHEET
            # that consumes it (components/slice9.css), not this document - so the
            # path must be written relative to components/, not to _gallery.html.
            style = (
                "--s9-src:url('../assets/slice9/%s/%s');--s9-slice:%s;--s9-width:%dpx;"
                % (m["id"], fr["src"], sl, fr["width"])
            )
            inner = "" if tag == "div" else ("placeholder='search'" if tag == "input" else "")
            box = ("width:150px;height:90px" if role in ("panel", "card") else "min-width:120px")
            content = "" if tag == "input" else label
            if tag == "input":
                cells.append("<input class='s9' style=\"%s%s\" %s>" % (style, box, inner))
            else:
                cells.append("<%s class='s9' style=\"%s%s\">%s</%s>" % (tag, style, box, content, tag))
        secs.append(
            "<section><h2>%s <small>%s &middot; %d&times;%d tile, %dpx corner</small></h2>"
            "<div class='row'>%s</div></section>"
            % (m["label"], m["library"], m["tile"], m["tile"], m["corner"], "".join(cells))
        )
    html = """<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Slice-9 atlas gallery</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700&display=swap">
<link rel="stylesheet" href="../../components/slice9.css">
<style>
 body{margin:0;background:#11131f;color:#e8eaf2;font-family:'Plus Jakarta Sans',system-ui,sans-serif;padding:28px 32px 80px}
 h1{font-size:22px;margin:0 0 4px} .lede{color:#9aa0c0;margin:0 0 26px;font-size:14px}
 section{margin:0 0 30px} h2{font-size:16px;margin:0 0 12px;letter-spacing:.02em}
 h2 small{color:#8b90b4;font-weight:400;font-size:12px;margin-left:8px}
 .row{display:flex;gap:18px;align-items:center;flex-wrap:wrap}
 .s9{color:#fff;display:inline-flex;align-items:center;justify-content:center;font-weight:600;font-size:14px}
 input.s9{color:#1a1c2c}
</style></head><body>
<h1>Slice-9 game-UI atlases</h1>
<p class="lede">Every skin &times; role, each cell driven by its <code>atlas.json</code> slice/width values via <code>border-image</code>. One raster per frame.</p>
%s
</body></html>""" % "\n".join(secs)
    with open(os.path.join(OUT_ROOT, "_gallery.html"), "w") as f:
        f.write(html)


def main():
    os.makedirs(OUT_ROOT, exist_ok=True)
    manifests = [build_skin(s) for s in SKINS]
    write_gallery(manifests)
    print("built %d skins:" % len(manifests), ", ".join(m["id"] for m in manifests))
    print("gallery:", os.path.normpath(os.path.join(OUT_ROOT, "_gallery.html")))


if __name__ == "__main__":
    main()
