#!/usr/bin/env python3
"""build_ds.py - generate a component design system's build/ folder.

    python3 build_ds.py --ds-dir <project>/design-systems/<id> [--strict] [--quiet]

Writes build/ds.css, build/ds-runtime.js, build/manifest.json, build/CATALOG.md
and build/gallery.html from the DS sources. Never hand-edit build/.
Spec: docs/features/component-ds-format.md. Stdlib only, Python 3.9-safe.

Exit codes: 0 built clean, 1 built with errors (or refused with --strict),
2 not a component design system.
"""

import argparse
import html as htmllib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import ds_model  # noqa: E402

RUNTIME_SRC = os.path.join(HERE, "runtime", "ds-runtime.src.js")
GENERATED_MARK = "GENERATED by editor/tools/ds/build_ds.py"
LAYER_TITLES = [("layout", "Layout"), ("atom", "Atoms"), ("molecule", "Molecules"), ("organism", "Organisms"),
                ("pattern", "Patterns"), ("shell", "Shells")]
URL_RE = re.compile(r"url\(\s*(['\"]?)([^'\")]+)\1\s*\)")
IMPORT_RE = re.compile(r"@import\s+(?:url\()?\s*['\"]?(https?:[^'\")\s]+|//[^'\")\s]+)['\"]?\s*\)?[^;]*;")


def _read(p):
    with open(p, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def _write(p, text):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tmp = p + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, p)


def _js_json(obj):
    """JSON safe to drop into a script (no closing script tag sequence)."""
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


# ── CSS bundle ───────────────────────────────────────────────────────────────
def _rewrite_urls(css, src_dir, build_dir):
    def sub(m):
        q, u = m.group(1), m.group(2).strip()
        if re.match(r"^([a-z]+:|//|#|/|var\()", u):
            return m.group(0)
        path, _, rest = u.partition("?")
        path, _, frag = path.partition("#")
        rel = os.path.relpath(os.path.normpath(os.path.join(src_dir, path)), build_dir).replace(os.sep, "/")
        if rest:
            rel += "?" + rest
        if frag:
            rel += "#" + frag
        return "url(" + q + rel + q + ")"
    return URL_RE.sub(sub, css)


def block_order(ds):
    """Every block with a style.css, in CSS order: by layer rank (layout, atom,
    molecule, organism, pattern, shell), then name, with each block's
    `contains` emitted BEFORE it so a parent's context rules win ties."""
    rank = dict((l, i) for i, l in enumerate(ds_model.LAYER_RANK))
    names = sorted(ds.blocks, key=lambda n: (rank.get(ds.blocks[n].spec.get("layer"), 99), n))
    out, seen = [], set()

    def visit(n, trail):
        if n in seen or n in trail or n not in ds.blocks:
            return
        b = ds.blocks[n]
        for c in sorted(b.spec.get("contains", []) or [], key=lambda c: (rank.get(ds.blocks[c].spec.get("layer"), 99), c) if c in ds.blocks else (99, c)):
            visit(c, trail | {n})
        seen.add(n)
        if b.style:
            out.append(n)
    for n in names:
        visit(n, set())
    return out


def build_css(ds, build_dir):
    """ONE plain stylesheet (no @layer): tokens, foundations, blocks, themes.
    Specificity and source order behave exactly like a hand-written single
    stylesheet, which is what a converted DS was verified against."""
    imports = []

    def take(path):
        css = _read(path)
        for m in IMPORT_RE.finditer(css):
            if m.group(0) not in imports:
                imports.append(m.group(0))
        css = IMPORT_RE.sub("", css)
        css = _rewrite_urls(css, os.path.dirname(path), build_dir)
        rel = os.path.relpath(path, ds.dir).replace(os.sep, "/")
        return "/* " + rel + " */\n" + css.strip() + "\n"

    groups = [("tokens", [p for k, p in ds.css_files if k == "tokens"]),
              ("foundations", [p for k, p in ds.css_files if k == "base"]),
              ("blocks", [ds.blocks[n].style for n in block_order(ds)]),
              ("themes", [p for k, p in ds.css_files if k == "themes"])]
    sections = []
    for title, files in groups:
        if files:
            sections.append("/* ==== " + title + " ==== */\n" + "\n".join(take(p) for p in files))
    head = ("/* GENERATED by editor/tools/ds/build_ds.py from design-systems/" + ds.id + "/ - do not edit.\n"
            "   Order: tokens, foundations, blocks (contained blocks first), themes. Pages never select a DS class. */\n")
    return head + "".join(i + "\n" for i in imports) + "\n" + "\n".join(sections)


# ── runtime ──────────────────────────────────────────────────────────────────
def manifest(ds, version):
    blocks = {}
    for name in sorted(ds.blocks):
        b = ds.blocks[name]
        s = b.spec
        blocks[name] = {
            "name": name, "title": s.get("title") or name, "layer": s.get("layer"), "kind": b.kind,
            "oneLine": s.get("oneLine", ""), "useWhen": s.get("useWhen", ""), "notForUseWhen": s.get("notForUseWhen", ""),
            "props": s.get("props", {}) or {}, "slots": s.get("slots"), "rootClass": b.root_class,
            "replaces": s.get("replaces", []) or [], "contains": s.get("contains", []) or [],
            "events": s.get("events", []) or [], "states": s.get("states", []) or [],
            "copy": s.get("copy", {}) or {}, "template": b.template.strip(),
            "examples": b.examples,
        }
    return {
        "id": ds.id, "label": ds.meta.get("label") or ds.id, "version": version, "format": ds_model.FORMAT,
        "blocks": blocks, "icons": ds.icons,
        "defaultIconStyle": ds.meta.get("defaultIconStyle") or ("filled" if "filled" in ds.icons else (sorted(ds.icons)[0] if ds.icons else "filled")),
        "services": [{"name": n, "desc": d} for n, d, _ in ds.services],
    }


def build_runtime(ds, man):
    parts = ["/* GENERATED by editor/tools/ds/build_ds.py from design-systems/" + ds.id + "/ (version " + man["version"] + ") - do not edit. */\n",
             _read(RUNTIME_SRC), "\n"]
    payload = dict(man)
    payload["blocks"] = dict((n, dict((k, v) for k, v in b.items() if k != "examples")) for n, b in man["blocks"].items())
    parts.append("DS.__load(" + _js_json(payload) + ");\n")
    for name, desc, path in ds.services:
        parts.append("\n/* services/" + os.path.basename(path) + " */\n;(function (DS) {\n" + _read(path).rstrip() + "\n})(window.DS);\n")
    for name in sorted(ds.blocks):
        b = ds.blocks[name]
        if b.behavior:
            rel = os.path.relpath(b.behavior, ds.dir).replace(os.sep, "/")
            parts.append("\n/* " + rel + " */\n;(function (DS) {\n" + _read(b.behavior).rstrip() + "\n})(window.DS);\n")
    parts.append("\nDS.__boot();\n")
    return "".join(parts)


# ── catalog ──────────────────────────────────────────────────────────────────
def _sig(b):
    bits = []
    for pn, ps in (b["props"] or {}).items():
        t = ps.get("type", "string")
        s = pn + ("!" if ps.get("required") else "")
        if t == "enum":
            s += ":" + "|".join(str(v) for v in ps.get("values", []))
            if "default" in ps:
                s += "=" + str(ps["default"])
        elif t != "string":
            s += ":" + ("bool" if t == "boolean" else t)
            if "default" in ps:
                s += "=" + json.dumps(ps["default"])
        bits.append(s)
    out = "<ds-" + b["name"] + (" " + " ".join(bits) if bits else "") + ">"
    slots = b.get("slots")
    if slots:
        sl = []
        for sn, sp in slots.items():
            acc = sp.get("accepts", "any") if isinstance(sp, dict) else "any"
            sl.append(sn + "(" + ("|".join(acc) if isinstance(acc, list) else acc) + ")")
        out += " slots: " + ", ".join(sl)
    return out


def build_catalog(ds, man, ds_rel_hint):
    L = []
    L.append("# " + man["label"] + " - block catalog")
    L.append("")
    L.append("GENERATED from design-systems/" + ds.id + "/ (version " + man["version"] + "). Do not edit; edit the block folders and rebuild.")
    L.append("")
    L.append("Pages are built ONLY by placing these blocks. Rules:")
    L.append("1. Static markup: `<ds-name prop=\"value\">`. JS: `DS.html(\"name\", {props}, {slot: html})` returns final markup; never hand-write a block's classes.")
    L.append("2. Raw HTML only inside `<ds-custom reason=\"why no block fits\">`. Never style a DS class from a page; no inline styles on blocks.")
    L.append("3. In `<head>`: `<link rel=\"stylesheet\" href=\"" + ds_rel_hint + "/build/ds.css\">` and `<script src=\"" + ds_rel_hint + "/build/ds-runtime.js\"></script>`.")
    L.append("4. Passthrough attributes on any block: id, class (placement only), data-*, aria-*, hidden, title, role, tabindex. `slot=\"name\"` puts a child in a named slot.")
    L.append("5. Blocks talk through attributes and `ds:*` events; page JS listens with addEventListener. Persistent state (which tab is active) is a prop, never a class.")
    L.append("")
    L.append("Signature: `prop!` required, `prop:a|b=a` enum with default, `:bool` `:number` `:list` (comma-separated) `:json`. `slots: name(accepts)`.")
    for layer, title in LAYER_TITLES:
        rows = [b for b in man["blocks"].values() if b["layer"] == layer]
        if not rows:
            continue
        L.append("")
        L.append("## " + title)
        for b in sorted(rows, key=lambda x: x["name"]):
            line = _sig(b) + "  " + b["oneLine"].rstrip(".") + "."
            if b.get("useWhen"):
                line += " Use: " + b["useWhen"].rstrip(".") + "."
            if b.get("notForUseWhen"):
                line += " Not for: " + b["notForUseWhen"].rstrip(".") + "."
            if b.get("replaces"):
                line += " Replaces " + ", ".join("<" + r + ">" for r in b["replaces"]) + "."
            if b.get("events"):
                line += " Emits " + ", ".join(b["events"]) + "."
            L.append("- " + line)
    if man["services"]:
        L.append("")
        L.append("## Services (shared functions)")
        for s in man["services"]:
            L.append("- `DS." + s["name"] + "` " + (s["desc"] or ""))
    L.append("")
    L.append("## Runtime")
    L.append("- `DS.html(name, props, slots)` expanded markup string; `DS.expand(el)` expand <ds-*> tags inserted by hand; `DS.update(root, props)` re-render one block; `DS.props(root)`; `DS.emit(el, type, detail)`; `DS.icon(name, {style})`; `DS.ready(fn)`.")
    if man["icons"]:
        L.append("")
        styles = sorted(man["icons"])
        names = sorted(set(n for s in styles for n in man["icons"][s]))
        L.append("## Icons (" + str(len(names)) + "; styles: " + ", ".join(styles) + "; default " + man["defaultIconStyle"] + ")")
        if len(names) <= 600:
            L.append(", ".join(names))
        else:
            L.append("Too many to list; see build/manifest.json `icons`.")
    return "\n".join(L) + "\n"


# ── gallery ──────────────────────────────────────────────────────────────────
GALLERY_CSS = """
.dsg{display:grid;grid-template-columns:220px minmax(0,1fr);min-height:100vh;background:#fafafa}
.dsg-nav,.dsg-title,.dsg-sub,.dsg-h,.dsg-line,.dsg-ex-h,.dsg-sw-n,.dsg-ic{font:14px/1.5 system-ui,-apple-system,sans-serif;color:#1d1d1f}
.dsg-nav{position:sticky;top:0;height:100vh;overflow:auto;padding:20px 12px;border-right:1px solid #e3e3e6;background:#fff}
.dsg-nav-h{font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#86868b;margin:16px 8px 4px}
.dsg-nav-a{display:block;padding:3px 8px;border-radius:6px;color:#1d1d1f;text-decoration:none}
.dsg-nav-a:hover{background:#f0f0f2}
.dsg-main{padding:28px 36px;min-width:0}
.dsg-title{font-size:22px;font-weight:650;margin:0 0 4px}
.dsg-sub{color:#6e6e73;margin:0 0 24px}
.dsg-sec{margin:0 0 40px;padding-top:8px}
.dsg-h{font-size:17px;font-weight:650;margin:0 0 2px}
.dsg-tag{font:12px ui-monospace,Menlo,monospace;color:#6e6e73;margin-left:8px;font-weight:400}
.dsg-line{color:#3a3a3c;margin:2px 0}
.dsg-meta{font:12px ui-monospace,Menlo,monospace;color:#6e6e73;margin:6px 0 12px;white-space:pre-wrap}
.dsg-ex{border:1px solid #e3e3e6;border-radius:10px;background:#fff;margin:0 0 12px;overflow:hidden}
.dsg-ex-h{font-size:12px;color:#6e6e73;padding:6px 12px;border-bottom:1px solid #f0f0f2;display:flex;justify-content:space-between;gap:12px}
.dsg-ex-code{font:11px ui-monospace,Menlo,monospace;color:#86868b;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dsg-stage{padding:16px;overflow:auto}
.dsg-frame{width:100%;border:0;display:block}
.dsg-swatches{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:8px}
.dsg-sw{border:1px solid #e3e3e6;border-radius:8px;overflow:hidden;background:#fff;font:11px ui-monospace,Menlo,monospace}
.dsg-sw-c{height:40px}
.dsg-sw-n{padding:4px 6px;word-break:break-all}
.dsg-icons{display:grid;grid-template-columns:repeat(auto-fill,minmax(96px,1fr));gap:6px}
.dsg-ic{display:flex;flex-direction:column;align-items:center;gap:4px;padding:8px 4px;border:1px solid #f0f0f2;border-radius:8px;background:#fff;font:10px ui-monospace,Menlo,monospace;color:#6e6e73;text-align:center;word-break:break-all}
.dsg-ic svg{width:24px;height:24px;color:#1d1d1f}
.dsg-err{color:#b00020;font:12px ui-monospace,Menlo,monospace}
"""

GALLERY_JS = r"""
var CSS_HREF = document.querySelector('link[href*="ds.css"]').href;
var JS_HREF = document.querySelector('script[src*="ds-runtime.js"]').src;
DS.ready(function () {
  var stages = document.querySelectorAll("[data-dsg-example]");
  for (var i = 0; i < stages.length; i++) {
    var st = stages[i], ex;
    try { ex = JSON.parse(st.getAttribute("data-dsg-example")); } catch (e) { continue; }
    try {
      var markup = DS.html(ex.block, Object.assign({}, ex.props || {}, ex.attrs || {}), ex.slots || {});
      if (ex.frame) {
        var f = document.createElement("iframe");
        f.className = "dsg-frame";
        f.style.height = (ex.frame.height || 480) + "px";
        f.srcdoc = '<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="' + CSS_HREF + '"><script src="' + JS_HREF + '"><\/script></head><body>' + markup + '</body></html>';
        st.appendChild(f);
      } else {
        st.innerHTML = markup;
        DS.expand(st);
      }
    } catch (err) {
      st.innerHTML = '<div class="dsg-err"></div>';
      st.firstChild.textContent = String(err && err.message || err);
    }
  }
});
"""


def _e(s):
    return htmllib.escape(str(s), quote=True)


def _source_tag(name, props, slots):
    attrs = ""
    for k, v in (props or {}).items():
        if v is True:
            attrs += " " + k
        elif isinstance(v, (list, tuple)):
            attrs += " " + k + '="' + ",".join(str(x) for x in v) + '"'
        elif isinstance(v, (dict,)):
            attrs += " " + k + "='" + json.dumps(v) + "'"
        else:
            attrs += " " + k + '="' + str(v) + '"'
    inner = " ".join(("[" + k + "] " if k != "default" else "") + re.sub(r"\s+", " ", v).strip() for k, v in (slots or {}).items())
    return "<ds-" + name + attrs + ">" + inner + "</ds-" + name + ">"


def build_gallery(ds, man):
    tokens_css = ""
    for layer, p in ds.css_files:
        if layer == "tokens":
            tokens_css += _read(p)
    colors = re.findall(r"(--color-[\w-]+)\s*:", ds_model.strip_css_comments(tokens_css))
    other = [t for t in re.findall(r"(--[\w-]+)\s*:", ds_model.strip_css_comments(tokens_css)) if not t.startswith("--color-")]
    nav, body = [], []
    nav.append('<div class="dsg-nav-h">Foundations</div><a class="dsg-nav-a" href="#f-color">Colour</a><a class="dsg-nav-a" href="#f-tokens">Tokens</a>')
    sw = "".join('<div class="dsg-sw"><div class="dsg-sw-c" style="background:var(' + c + ')"></div><div class="dsg-sw-n">' + _e(c) + "</div></div>" for c in colors)
    body.append('<section class="dsg-sec" id="f-color"><h2 class="dsg-h">Colour</h2><div class="dsg-swatches">' + sw + "</div></section>")
    body.append('<section class="dsg-sec" id="f-tokens"><h2 class="dsg-h">Tokens</h2><div class="dsg-meta">' + _e(", ".join(other)) + "</div></section>")
    for layer, title in LAYER_TITLES:
        rows = sorted((b for b in man["blocks"].values() if b["layer"] == layer), key=lambda x: x["name"])
        if not rows:
            continue
        nav.append('<div class="dsg-nav-h">' + _e(title) + "</div>")
        for b in rows:
            nav.append('<a class="dsg-nav-a" href="#b-' + _e(b["name"]) + '">' + _e(b["title"]) + "</a>")
            meta = _sig(b)
            info = []
            if b.get("useWhen"):
                info.append("Use: " + b["useWhen"])
            if b.get("notForUseWhen"):
                info.append("Not for: " + b["notForUseWhen"])
            if b.get("replaces"):
                info.append("Replaces: " + ", ".join("<" + r + ">" for r in b["replaces"]))
            if b.get("events"):
                info.append("Events: " + ", ".join(b["events"]))
            exs = []
            for ex in b.get("examples") or []:
                if not isinstance(ex, dict):
                    continue
                data = {"block": b["name"], "props": ex.get("props") or {}, "slots": ex.get("slots") or {},
                        "attrs": ex.get("attrs") or {}, "frame": ex.get("frame")}
                exs.append('<div class="dsg-ex"><div class="dsg-ex-h"><span>' + _e(ex.get("title", "")) + '</span><span class="dsg-ex-code">'
                           + _e(_source_tag(b["name"], ex.get("props"), ex.get("slots"))) + '</span></div><div class="dsg-stage" data-dsg-example="'
                           + _e(json.dumps(data)) + '"></div></div>')
            body.append('<section class="dsg-sec" id="b-' + _e(b["name"]) + '"><h2 class="dsg-h">' + _e(b["title"]) + '<span class="dsg-tag">&lt;ds-'
                        + _e(b["name"]) + '&gt;</span></h2><p class="dsg-line">' + _e(b["oneLine"]) + '</p><div class="dsg-meta">'
                        + _e(meta + ("\n" + "\n".join(info) if info else "")) + "</div>" + "".join(exs) + "</section>")
    if man["services"]:
        nav.append('<div class="dsg-nav-h">Services</div><a class="dsg-nav-a" href="#f-services">Services</a>')
        body.append('<section class="dsg-sec" id="f-services"><h2 class="dsg-h">Services</h2><div class="dsg-meta">'
                    + _e("\n".join("DS." + s["name"] + "  " + s["desc"] for s in man["services"])) + "</div></section>")
    for style in sorted(man["icons"]):
        nav.append('<a class="dsg-nav-a" href="#f-icons-' + _e(style) + '">Icons: ' + _e(style) + "</a>")
        cells = "".join('<div class="dsg-ic"><svg viewBox="' + _e(d["v"]) + '" fill="currentColor" aria-hidden="true">' + d["b"] + "</svg>" + _e(n) + "</div>"
                        for n, d in sorted(man["icons"][style].items()))
        body.append('<section class="dsg-sec" id="f-icons-' + _e(style) + '"><h2 class="dsg-h">Icons: ' + _e(style) + '</h2><div class="dsg-icons">' + cells + "</div></section>")
    return ("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
            "<title>" + _e(man["label"]) + " blocks</title>\n<link rel=\"stylesheet\" href=\"ds.css\">\n<script src=\"ds-runtime.js\"></script>\n"
            "<style>" + GALLERY_CSS + "</style>\n</head>\n<body>\n<!-- GENERATED by editor/tools/ds/build_ds.py - do not edit -->\n"
            "<div class=\"dsg\" data-ds-gallery-chrome>\n<nav class=\"dsg-nav\">" + "".join(nav) + "</nav>\n<main class=\"dsg-main\"><h1 class=\"dsg-title\">"
            + _e(man["label"]) + "</h1><p class=\"dsg-sub\">" + str(len(man["blocks"])) + " blocks, version " + _e(man["version"]) + "</p>\n"
            + "\n".join(body) + "\n</main>\n</div>\n<script>" + GALLERY_JS + "</script>\n</body>\n</html>\n")


# ── main ─────────────────────────────────────────────────────────────────────
def build(ds_dir, strict=False):
    """Returns (ds, wrote: bool). ds is None when not a component DS."""
    ds = ds_model.load(ds_dir)
    if ds.kind != "component":
        return None, False
    errors = [f for f in ds.findings if f.level == "error"]
    if strict and errors:
        return ds, False
    build_dir = os.path.join(ds.dir, "build")
    version = ds.version()
    man = manifest(ds, version)
    _write(os.path.join(build_dir, "ds.css"), build_css(ds, build_dir))
    _write(os.path.join(build_dir, "ds-runtime.js"), build_runtime(ds, man))
    _write(os.path.join(build_dir, "manifest.json"), json.dumps(man, indent=1, ensure_ascii=False) + "\n")
    _write(os.path.join(build_dir, "CATALOG.md"), build_catalog(ds, man, "../../design-systems/" + ds.id))
    gallery = build_gallery(ds, man)
    _write(os.path.join(build_dir, "gallery.html"), gallery)
    # The editor's DS surfaces (DS node, library viewer, global DS sync) open
    # <ds>/gallery.html. Mirror the generated gallery there, but never over a
    # hand-written one (a DS mid-conversion still has its legacy gallery).
    root_gallery = os.path.join(ds.dir, "gallery.html")
    if not os.path.exists(root_gallery) or GENERATED_MARK in _read(root_gallery)[:4000]:
        _write(root_gallery, gallery.replace('href="ds.css"', 'href="build/ds.css"').replace('src="ds-runtime.js"', 'src="build/ds-runtime.js"'))
    return ds, True


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate a component design system's build/ folder")
    ap.add_argument("--ds-dir", required=True)
    ap.add_argument("--strict", action="store_true", help="refuse to write build/ when the DS has errors")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args(argv)
    ds, wrote = build(a.ds_dir, a.strict)
    if ds is None:
        print("build_ds: " + a.ds_dir + " is not a component design system (meta.json kind)")
        return 2
    counts = {"error": 0, "warn": 0, "info": 0}
    for f in ds.findings:
        counts[f.level] = counts.get(f.level, 0) + 1
    if not a.quiet:
        for f in sorted(ds.findings, key=lambda f: ({"error": 0, "warn": 1}.get(f.level, 2), f.file or "", f.line or 0)):
            print(f.fmt(os.getcwd()))
    print("build_ds " + ds.id + ": " + ("wrote build/ (" + str(len(ds.blocks)) + " blocks)" if wrote else "NOT written (--strict)")
          + ", " + str(counts["error"]) + " errors, " + str(counts["warn"]) + " warnings")
    return 1 if counts["error"] else 0


if __name__ == "__main__":
    sys.exit(main())
